import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import ServiceWorkerRegister from '@/components/pwa/sw-register';

import './globals.css';

// One family for everything — headings, body and the hero figures. Self-hosted
// by next/font at build time (no runtime request to a font CDN).
const sans = Geist({
  variable: '--font-geist',
  subsets: ['latin'],
  display: 'swap',
});

const mono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Work Optional — find out when work becomes optional',
  description:
    'Project net worth year by year from your own assumptions. Runs entirely in your browser — no login, nothing stored.',
  // A standalone planning tool should be findable if shared by URL.
  robots: { index: true, follow: true },
  applicationName: 'Work Optional',
  // Manifest is generated by src/app/manifest.ts at build time.
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    // 'black-translucent' lets the app background bleed under the status
    // bar so the dark theme covers the whole screen on iOS.
    statusBarStyle: 'black-translucent',
    title: 'Work Optional',
  },
  // formatDetection prevents iOS from auto-linking phone numbers / dates
  // in our number-heavy UI, which would otherwise turn tabular figures
  // into accidental tap targets.
  formatDetection: { telephone: false, date: false, address: false, email: false },
};

export const viewport: Viewport = {
  themeColor: '#0b0b0c',
  width: 'device-width',
  initialScale: 1,
  // Disable user scaling so the bottom nav stays where it belongs on iOS.
  maximumScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        {children}
        <ServiceWorkerRegister />
      </body>
    </html>
  );
}
